### ISSUE TITLE
Can this be used with Alexa Skills Kit?

### ISSUE THREAD

**Issue by dly9014** [RationalAnimal/vui-ad-hoc-alexa-recognizer#2084]
Just found your incredible work and I'm wondering if it can be used for fulfilllment of Alexa intents or if it is just meant to be an alternative to using Alexa / ASK. It seems like if it was possible to get the raw spoken utterance from a user, additional checks could be done with your code to determine if Amazon determined the correct intent (because you could dynamically include custom slot values and corresponding process logic which you can't do with ASK). But I guess it is a mute point since you can't get the raw spoken utterance that a user says to Alexa can you?

**Comment by RationalAnimal** [comment]
I am pretty sure you are right - at this point Amazon does not provide raw user text.  There is a possibility that you may be able to get it using their literal slot type (I think that's what it's called).  It used to be there, then they took it away, then they brought it back, and I don't know what the current status is.  I don't like to rely on things that are that uncertain, so I am not keeping track of its current availability.  I wouldn't rely on it being there long term, but it's possible. Having dealt with Amazon's solutions architects I know it's not a technical issue, but rather a security/perception concern.  They don't want customers to ever think that Alexa is snooping on them.  But they seem to be relaxing other restrictions a little bit as they get more experience with user acceptance, so it's possible.
To get back to your question though, at this time it's not meant to be used with Alexa parsing, but you can use it with Alexa development to simplify the utterance handling.  I found that writing by hand all the permutations of acceptable utterances was a pain, thus I wrote the alexify utility.  I use it myself in my "day job" to manage utterances.  But it's only working reliably for the older style of the interaction model.  While there is code to support the new beta interaction model, there are issues with it and I didn't want to spend time debugging it before they finalize it.  Once they do I'll probably fix any issues in the related code.  Google assistant or Cortana (at least the original Cortana model) are much better use cases.  If you are looking at using MS bot framework, you might be able to convert vui-ad-hoc-alexa-recognizer so that it can plug into the MS bot framework as an alternative to Luis.  I am not currently pursuing this as MS bot framework doesn't seem to have much traction in the market.  I am also going to be putting together examples/tutorials of using this within mobile apps and browser, but there is only so much time in a 24 hour day.  Also, there is another related project I am playing with - GUI for creating the interaction and conversation flows.  I find that most/all tools out there for doing this are approaching it from the "traditional" angle.  They are mostly form based or similar to that and it simply doesn't provide a good experience.  So, trying to figure out the priorities.  If you have any specific needs please feel free to request features.  I've asked the users to do so, but so far everybody seems to be content with just downloading whatever I provide.
